version: '3'

services:
  nginx-PROJECTNAME:
    image: nginx:latest
    expose:
      - 80
    volumes:
      - ./htdocs:/usr/share/nginx/htdocs
      - ./nginx:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: PROJECTDOMAIN
      VIRTUAL_PORT: 80
    links:
      - php-PROJECTNAME

  php-PROJECTNAME:
    user: "1001:33"
    build:
      context: .
      dockerfile: php-Dockerfile
    volumes:
      - ./htdocs:/usr/share/nginx/htdocs

  mariadb-PROJECTNAME:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password

  redis-PROJECTNAME:
    image: redis:latest

  # You probably want to keep the container below only in production
  tools-PROJECTNAME:
    user: "1001:33"
    build:
      context: .
      dockerfile: tools-Dockerfile
    volumes:
      - ./htdocs:/project
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  code:
    driver: local